import type { BlogBlock, BlogPost } from './blog-data';

const contactHref = '/contato#contato-form';

function paragraph(text: string): BlogBlock { return { type: 'paragraph', text }; }
function heading(text: string): BlogBlock { return { type: 'heading', text }; }
function subheading(text: string): BlogBlock { return { type: 'subheading', text }; }
function list(items: string[]): BlogBlock { return { type: 'list', items }; }
function diagram(text: string): BlogBlock { return { type: 'code', text }; }
function callout(text: string, cta = 'Solicitar diagnóstico'): BlogBlock { return { type: 'quote', text, cta, href: contactHref }; }

function images(slug: string, category: string, query: string): BlogPost['imageSuggestions'] {
  return [
    { label: 'Capa do artigo', source: 'Imagem editorial gerada/curada', query, path: `/images/blog/${slug}-cover.jpg`, alt: `Imagem editorial sobre ${category} aplicada a negócios digitais.` },
    { label: 'Imagem de apoio', source: 'Imagem editorial gerada/curada', query: `${query} workflow`, path: `/images/blog/${slug}-apoio.jpg`, alt: `Visual de apoio sobre ${category} em fluxo de trabalho.` },
    { label: 'Open Graph', source: 'Imagem editorial gerada/curada', query: `${query} abstract interface`, path: `/images/blog/${slug}-og.jpg`, alt: `Imagem social sobre ${category} no contexto da Tehkné Solutions.` }
  ];
}

export const newBlogPosts: BlogPost[] = [
  {
    title: 'Manutenção de sites WordPress: o que monitorar todo mês para evitar risco e perda de vendas',
    slug: 'manutencao-de-sites-wordpress-o-que-monitorar-todo-mes',
    description: 'Checklist completo de manutenção de sites WordPress: atualizações, backups, segurança, performance, formulários, SEO técnico, plugins e gestão de melhorias.',
    category: 'Manutenção e Gestão',
    tags: ['Manutenção de sites', 'WordPress', 'Segurança', 'Backups', 'Performance'],
    cover: '/images/blog/manutencao-de-sites-wordpress-o-que-monitorar-todo-mes-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-03',
    readingTime: '16 min de leitura',
    intro: 'Um site WordPress em produção não pode ser tratado como algo que foi publicado e esquecido. Ele precisa de rotina técnica para continuar seguro, rápido, estável e preparado para campanhas, SEO e geração de leads.',
    imageSuggestions: images('manutencao-de-sites-wordpress-o-que-monitorar-todo-mes', 'Manutenção de sites WordPress', 'wordpress maintenance security backup performance'),
    blocks: [
      paragraph('Manutenção de site WordPress não é apenas apertar o botão de atualizar plugins. Uma rotina profissional envolve backup, validação, segurança, testes de formulário, performance, SEO técnico, revisão de acessos, análise de erros, monitoramento de páginas importantes e organização de melhorias.'),
      paragraph('O problema é que muitas empresas só lembram da manutenção quando o site sai do ar, o formulário para de enviar, uma campanha perde conversão ou uma atualização quebra o layout. Nesse ponto, o custo já é maior porque o time está reagindo a uma emergência.'),
      heading('Por que WordPress exige manutenção contínua?'),
      paragraph('WordPress é uma excelente base para sites, blogs, catálogos, portais e operações editoriais. Mas sua flexibilidade vem acompanhada de dependências: tema, plugins, integrações, banco de dados, hospedagem, cache, formulários, páginas, imagens, permissões e versões. Cada elemento precisa ser acompanhado.'),
      list(['Plugins recebem atualizações de segurança e compatibilidade.', 'Temas podem mudar comportamento após novas versões.', 'Formulários dependem de envio, SMTP, webhooks ou integrações.', 'Cache pode esconder erros ou atrasar mudanças.', 'Ataques automatizados procuram instalações desatualizadas.', 'Campanhas exigem páginas rápidas, confiáveis e mensuráveis.']),
      heading('Checklist mensal de manutenção WordPress'),
      subheading('1. Backups e restauração'),
      paragraph('Backup só é útil se puder ser restaurado. A rotina precisa verificar se os backups estão sendo gerados, onde estão armazenados, qual frequência possuem e se existe plano de rollback antes de grandes alterações.'),
      list(['Backup de arquivos.', 'Backup de banco de dados.', 'Armazenamento fora da hospedagem principal.', 'Teste periódico de restauração.', 'Registro da última cópia válida.']),
      subheading('2. Atualizações controladas'),
      paragraph('Atualizar tudo sem critério pode quebrar. Nunca atualizar aumenta risco. A solução é criar um fluxo: backup, atualização, validação de páginas críticas, teste de formulários e registro do que mudou.'),
      subheading('3. Segurança e acessos'),
      list(['Revisar usuários administradores.', 'Remover contas antigas.', 'Ativar autenticação em duas etapas quando possível.', 'Monitorar tentativas de login.', 'Evitar plugins abandonados.', 'Manter senhas fortes e permissões adequadas.']),
      subheading('4. Performance e Core Web Vitals'),
      paragraph('Um site lento prejudica experiência, SEO e campanhas pagas. A manutenção deve acompanhar peso de imagens, scripts, cache, fontes, plugins pesados e páginas com maior tráfego.'),
      subheading('5. Formulários e conversão'),
      paragraph('Um dos erros mais caros é ter formulário quebrado sem perceber. Todo mês, teste envios, integrações, mensagens de confirmação, WhatsApp, eventos de Analytics e destino dos leads.'),
      heading('SEO técnico também entra na manutenção'),
      paragraph('SEO não termina no lançamento. Páginas podem sair do ar, URLs podem mudar, imagens podem perder alt text, sitemap pode ficar incompleto e conteúdos podem precisar de atualização. Uma rotina de manutenção deve revisar indexação, títulos, metas, links internos e erros 404.'),
      heading('Manutenção corretiva, preventiva e evolutiva'),
      list(['Corretiva: resolve erros, bugs e falhas já identificadas.', 'Preventiva: evita problemas com atualização, segurança, backup e monitoramento.', 'Evolutiva: melhora páginas, adiciona seções, ajusta CTA, cria novos conteúdos e acompanha campanhas.']),
      heading('Quando contratar uma gestão técnica mensal?'),
      list(['Quando o site gera leads ou vendas.', 'Quando há campanhas ativas.', 'Quando existe blog, SEO ou páginas de serviço importantes.', 'Quando a empresa não tem time técnico interno.', 'Quando o WordPress possui integrações, formulários, WooCommerce ou plugins críticos.']),
      callout('A Tehkné pode estruturar uma rotina de manutenção e gestão técnica para manter seu WordPress seguro, rápido e preparado para evoluir.', 'Avaliar manutenção WordPress')
    ]
  },
  {
    title: 'Gestão técnica de sites: como evitar que sua operação digital vire um conjunto de remendos',
    slug: 'gestao-tecnica-de-sites-como-evitar-remendos',
    description: 'Entenda como gestão técnica, backlog, documentação, governança e priorização mantêm sites e sistemas organizados depois do lançamento.',
    category: 'Manutenção e Gestão',
    tags: ['Gestão técnica', 'Governança', 'Backlog', 'Sites', 'Sustentação'],
    cover: '/images/blog/gestao-tecnica-de-sites-como-evitar-remendos-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-04',
    readingTime: '15 min de leitura',
    intro: 'Muitos sites não ficam ruins de uma vez. Eles se tornam confusos aos poucos: uma landing page urgente, um plugin improvisado, uma seção duplicada, um formulário sem rastreio, uma integração sem documentação.',
    imageSuggestions: images('gestao-tecnica-de-sites-como-evitar-remendos', 'Gestão técnica de sites', 'website technical management governance backlog'),
    blocks: [
      paragraph('Gestão técnica de sites é a prática de manter a evolução digital organizada. Ela cria critérios para decidir o que entra, quando entra, como é validado, quem aprova e como fica documentado. Sem essa camada, o site vira uma soma de urgências.'),
      paragraph('Remendo técnico nem sempre nasce de má intenção. Muitas vezes nasce da pressa. O problema é que cada ajuste sem método aumenta a complexidade invisível do projeto. Depois de alguns meses, ninguém sabe por que uma seção existe, qual plugin controla determinado comportamento ou se pode apagar uma página antiga.'),
      heading('O que é gestão técnica na prática?'),
      list(['Organizar solicitações em backlog.', 'Priorizar por impacto e risco.', 'Documentar decisões importantes.', 'Separar correção, melhoria e nova funcionalidade.', 'Validar alterações antes de publicar.', 'Monitorar performance, SEO e conversão.', 'Criar rotina de revisão e evolução.']),
      heading('A diferença entre suporte e gestão'),
      paragraph('Suporte responde demandas. Gestão organiza o ciclo de vida da solução. Um suporte pode corrigir um botão quebrado. A gestão pergunta por que quebrou, onde mais pode acontecer, como testar, como documentar e se aquela página ainda faz sentido no funil.'),
      heading('Como montar um backlog saudável para site'),
      list(['Registrar toda demanda com contexto.', 'Classificar por tipo: bug, melhoria, conteúdo, SEO, campanha, integração ou segurança.', 'Definir prioridade: crítica, alta, média ou baixa.', 'Vincular cada item a uma página, métrica ou objetivo.', 'Evitar executar tarefas sem critério de aceite.', 'Revisar pendências em ciclos semanais ou quinzenais.']),
      heading('Sinais de que o site virou remendo'),
      list(['Existem páginas duplicadas ou abandonadas.', 'Ninguém sabe onde editar certos conteúdos.', 'Plugins foram instalados para resolver problemas pontuais.', 'O layout muda de padrão entre páginas.', 'Formulários enviam para destinos diferentes sem controle.', 'O site não tem documentação mínima.', 'Cada alteração gera medo de quebrar algo.']),
      subheading('Gestão técnica e SEO'),
      paragraph('SEO sofre quando o site vira remendo. Páginas competem pela mesma palavra-chave, links internos ficam confusos, URLs antigas permanecem indexadas, metadados se repetem e conteúdos não acompanham mudanças de oferta. Gestão técnica ajuda a manter a arquitetura do site coerente.'),
      heading('Fluxo recomendado pela Tehkné'),
      diagram('Demanda\n        ↓\nClassificação\n        ↓\nPriorização\n        ↓\nExecução técnica\n        ↓\nValidação\n        ↓\nDocumentação\n        ↓\nMonitoramento'),
      paragraph('Esse fluxo não engessa. Ele protege. A empresa continua evoluindo rápido, mas com menos risco, menos retrabalho e mais previsibilidade.'),
      callout('Se seu site tem muitas alterações soltas, a Tehkné pode organizar backlog, manutenção, documentação e plano de evolução.', 'Organizar gestão técnica')
    ]
  },
  {
    title: 'Segurança em WordPress: plugins, backups, atualizações e boas práticas para empresas',
    slug: 'seguranca-em-wordpress-plugins-backups-atualizacoes',
    description: 'Guia prático de segurança em WordPress para empresas: atualizações, plugins, backups, usuários, autenticação, hospedagem e monitoramento.',
    category: 'WordPress Avançado',
    tags: ['Segurança WordPress', 'Plugins', 'Backups', 'Atualizações', 'LGPD'],
    cover: '/images/blog/seguranca-em-wordpress-plugins-backups-atualizacoes-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-05',
    readingTime: '16 min de leitura',
    intro: 'WordPress pode ser seguro, mas não por acaso. Segurança depende de rotina, escolhas técnicas, atualizações controladas, revisão de plugins, backup confiável e gestão de acessos.',
    imageSuggestions: images('seguranca-em-wordpress-plugins-backups-atualizacoes', 'Segurança WordPress', 'wordpress security firewall backup login protection'),
    blocks: [
      paragraph('O maior risco em WordPress quase nunca é o WordPress em si. O risco costuma estar em instalação abandonada, plugins desatualizados, senhas fracas, hospedagem ruim, falta de backup, usuários antigos e ausência de monitoramento.'),
      paragraph('Para empresas, segurança não pode ser tratada como configuração única. Ela precisa fazer parte da manutenção. Cada novo plugin, formulário, integração ou usuário pode mudar a superfície de risco.'),
      heading('Pilares de segurança em WordPress'),
      list(['Atualizações controladas.', 'Plugins confiáveis e necessários.', 'Backups testados.', 'Controle de usuários e permissões.', 'Proteção de login.', 'Hospedagem estável.', 'Monitoramento de arquivos e erros.', 'Documentação de mudanças.']),
      heading('Plugins: menos é mais'),
      paragraph('Cada plugin adiciona código de terceiros ao projeto. Isso não significa que plugins sejam ruins. Significa que precisam ser escolhidos com critério: reputação, frequência de atualização, compatibilidade, função clara e possibilidade de substituição.'),
      list(['Remova plugins inativos.', 'Evite plugins abandonados.', 'Não instale vários plugins com a mesma função.', 'Documente plugins críticos.', 'Teste atualizações antes de publicar em produção quando o site for crítico.']),
      heading('Backup não é luxo'),
      paragraph('Backup é a diferença entre incidente e desastre. Um backup profissional precisa incluir arquivos e banco de dados, ser armazenado fora do servidor principal e ter restauração testada. Backup que nunca foi testado é apenas uma esperança.'),
      heading('Usuários e permissões'),
      list(['Evite compartilhar conta admin.', 'Use perfis de usuário adequados.', 'Remova acessos de antigos fornecedores.', 'Ative autenticação em duas etapas quando possível.', 'Revise administradores periodicamente.', 'Não use senhas simples ou repetidas.']),
      heading('Segurança e LGPD'),
      paragraph('Sites que coletam leads lidam com dados pessoais. Isso exige cuidado com formulários, armazenamento, destino das informações, consentimento, política de privacidade e proteção contra acesso indevido. Segurança técnica e privacidade caminham juntas.'),
      heading('Rotina mínima recomendada'),
      list(['Revisão mensal de plugins e tema.', 'Backup antes de alterações importantes.', 'Teste de formulário e envio.', 'Revisão de usuários.', 'Monitoramento de erros.', 'Verificação de páginas críticas.', 'Registro das mudanças realizadas.']),
      callout('A Tehkné pode revisar a segurança do seu WordPress e criar uma rotina de manutenção com backups, atualizações e governança.', 'Revisar segurança WordPress')
    ]
  },
  {
    title: 'SEO técnico recorrente: por que SEO não termina no lançamento do site',
    slug: 'seo-tecnico-recorrente-nao-termina-no-lancamento',
    description: 'Entenda por que SEO técnico precisa de manutenção recorrente: sitemap, indexação, performance, links internos, metadados, conteúdo e páginas de serviço.',
    category: 'SEO e Performance',
    tags: ['SEO técnico', 'Indexação', 'Performance', 'Sitemap', 'Conteúdo'],
    cover: '/images/blog/seo-tecnico-recorrente-nao-termina-no-lancamento-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-06',
    readingTime: '15 min de leitura',
    intro: 'SEO não é uma tarefa única feita no dia do lançamento. Buscadores mudam, concorrentes publicam, páginas envelhecem, conteúdos perdem contexto e problemas técnicos aparecem com o tempo.',
    imageSuggestions: images('seo-tecnico-recorrente-nao-termina-no-lancamento', 'SEO técnico recorrente', 'technical SEO sitemap performance search console'),
    blocks: [
      paragraph('Um site pode nascer com boa estrutura e mesmo assim perder força se não for mantido. SEO técnico recorrente acompanha indexação, performance, links internos, metadados, sitemap, páginas órfãs, erros 404, redirecionamentos e atualização de conteúdos.'),
      paragraph('Para empresas que dependem do site para autoridade e geração de oportunidades, SEO precisa virar rotina. Não basta instalar plugin, escrever título e esperar o Google entender tudo para sempre.'),
      heading('O que revisar em SEO técnico todo mês'),
      list(['Sitemap atualizado.', 'Robots e páginas indexáveis.', 'Erros 404.', 'Redirecionamentos.', 'Títulos e descriptions duplicados.', 'Performance mobile.', 'Imagens pesadas.', 'Links internos quebrados.', 'Páginas importantes sem CTA.', 'Conteúdos antigos que precisam ser atualizados.']),
      heading('SEO de página de serviço'),
      paragraph('Páginas de serviço são ativos comerciais. Elas precisam trabalhar intenção de busca, dor do cliente, promessa, entregáveis, processo, FAQ, CTA e prova. Uma página genérica dificilmente compete com conteúdos mais específicos.'),
      subheading('Exemplo'),
      paragraph('Em vez de apenas dizer “fazemos manutenção”, uma página mais forte trabalha termos como manutenção de sites, suporte WordPress, gestão técnica, backups, atualizações, segurança, performance e SEO técnico recorrente. Isso aumenta a cobertura semântica e melhora a clareza comercial.'),
      heading('Conteúdo antigo também precisa evoluir'),
      paragraph('Posts de blog podem começar com 700 palavras e depois virar pilares de 2.000 palavras. A cada atualização, eles podem ganhar exemplos, FAQ, links internos, checklists, dados, novas seções e conexão com serviços. Isso melhora utilidade e reforça autoridade.'),
      heading('Links internos como arquitetura de autoridade'),
      list(['Posts devem apontar para páginas de serviço relacionadas.', 'Páginas de serviço devem apontar para artigos educativos.', 'Cases devem apontar para serviços executados.', 'Produtos devem apontar para posts que explicam problemas que resolvem.', 'CTAs devem conduzir para diagnóstico ou contato.']),
      heading('SEO técnico e performance'),
      paragraph('Velocidade, estabilidade visual e experiência mobile impactam navegação e campanhas. Mesmo quando o ranking não muda imediatamente, páginas lentas reduzem conversão. SEO técnico e UX caminham juntos.'),
      callout('A Tehkné pode transformar SEO técnico em rotina: revisão, priorização, melhorias e criação de conteúdo conectado às páginas comerciais.', 'Planejar SEO recorrente')
    ]
  },
  {
    title: 'Tema próprio ou Elementor: qual caminho escolher em projetos WordPress profissionais?',
    slug: 'tema-proprio-ou-elementor-wordpress-profissional',
    description: 'Comparativo entre tema próprio, Elementor e abordagem híbrida para sites WordPress profissionais, considerando performance, autonomia, manutenção e escalabilidade.',
    category: 'WordPress Avançado',
    tags: ['WordPress', 'Elementor', 'Tema próprio', 'Performance', 'Manutenção'],
    cover: '/images/blog/tema-proprio-ou-elementor-wordpress-profissional-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-07',
    readingTime: '15 min de leitura',
    intro: 'A escolha entre tema próprio e Elementor não deve ser uma disputa de preferência. Ela deve nascer do objetivo do projeto, da equipe que vai operar, da necessidade de performance e da complexidade técnica.',
    imageSuggestions: images('tema-proprio-ou-elementor-wordpress-profissional', 'WordPress profissional', 'wordpress elementor custom theme development'),
    blocks: [
      paragraph('Elementor pode acelerar produção, facilitar edição e permitir autonomia visual. Tema próprio pode entregar mais controle, performance, consistência e menor dependência. Em muitos projetos, o melhor caminho é híbrido: usar WordPress como CMS, criar componentes sob medida e limitar o editor visual ao que realmente precisa ser editável.'),
      heading('Quando Elementor faz sentido'),
      list(['Landing pages com muita edição de conteúdo.', 'Times de marketing que precisam testar blocos rapidamente.', 'Projetos com orçamento menor e prazo curto.', 'Sites em que autonomia visual é prioridade.', 'Páginas que não possuem regras de negócio complexas.']),
      heading('Quando tema próprio é melhor'),
      list(['Sites premium com identidade muito específica.', 'Projetos que exigem performance forte.', 'Páginas dinâmicas com dados estruturados.', 'Catálogos, filtros e integrações.', 'Operações que precisam de código limpo e manutenção previsível.']),
      heading('O risco de misturar tudo no editor visual'),
      paragraph('O problema não é usar Elementor. O problema é colocar lógica de negócio, scripts críticos, integrações e estrutura de dados dentro de uma camada visual. Isso dificulta manutenção, versionamento e continuidade.'),
      heading('Abordagem híbrida recomendada'),
      diagram('WordPress\n├── Tema próprio: layout, componentes e performance\n├── Elementor: páginas editáveis quando fizer sentido\n├── Plugin próprio: regras e integrações\n├── CPTs: dados estruturados\n└── Governança: backup, documentação e manutenção'),
      paragraph('Essa abordagem dá autonomia sem abrir mão da engenharia. O cliente edita o que precisa, o código protege o que é crítico e o projeto continua evoluindo com menos risco.'),
      heading('Critérios para decidir'),
      list(['Quem vai editar o conteúdo?', 'Qual nível de performance é necessário?', 'Há integrações ou dados estruturados?', 'O layout precisa ser muito customizado?', 'O site terá manutenção recorrente?', 'O projeto pode crescer para sistema, catálogo ou portal?']),
      callout('A Tehkné define a melhor arquitetura WordPress conforme objetivo, operação e manutenção, sem cair em escolha automática de ferramenta.', 'Definir arquitetura WordPress')
    ]
  },
  {
    title: 'Plugin próprio no WordPress: quando vale a pena criar em vez de instalar mais um plugin',
    slug: 'plugin-proprio-wordpress-quando-vale-a-pena',
    description: 'Entenda quando criar um plugin próprio no WordPress para organizar regras, integrações, CPTs, automações e funcionalidades sob medida.',
    category: 'WordPress Avançado',
    tags: ['Plugin próprio', 'WordPress', 'CPT', 'Integrações', 'APIs'],
    cover: '/images/blog/plugin-proprio-wordpress-quando-vale-a-pena-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-08',
    readingTime: '16 min de leitura',
    intro: 'Instalar plugin é rápido. Criar plugin próprio exige engenharia. Mas em muitos projetos profissionais, o plugin próprio é o que impede o WordPress de virar uma pilha de dependências sem governança.',
    imageSuggestions: images('plugin-proprio-wordpress-quando-vale-a-pena', 'Plugin próprio WordPress', 'wordpress custom plugin api development'),
    blocks: [
      paragraph('Um plugin próprio centraliza regras que pertencem ao projeto: CPTs, campos, shortcodes, endpoints, integrações, permissões, automações e validações. Em vez de espalhar lógica pelo tema, functions.php, editor visual ou vários plugins, o projeto ganha uma camada organizada.'),
      heading('Quando criar plugin próprio'),
      list(['Quando existem tipos de conteúdo personalizados.', 'Quando há integrações com CRM, ERP, WhatsApp ou APIs.', 'Quando regras não devem depender do tema.', 'Quando o painel precisa de telas próprias.', 'Quando o projeto precisa ser mantido por anos.', 'Quando plugins genéricos criam dependência ou excesso de peso.']),
      heading('O que pode entrar em um plugin próprio'),
      list(['CPTs e taxonomias.', 'Campos personalizados.', 'Endpoints REST.', 'Webhooks.', 'Rotinas de importação ou exportação.', 'Integrações com serviços externos.', 'Validações de formulário.', 'Shortcodes ou blocos controlados.', 'Configurações administrativas.']),
      heading('Tema não é lugar para regra de negócio'),
      paragraph('O tema deve cuidar da apresentação. Se uma regra importante fica no tema, trocar layout pode quebrar funcionalidade. Plugin próprio preserva lógica mesmo quando o visual muda.'),
      heading('Exemplo prático'),
      paragraph('Um site de concessionária pode ter CPT de veículos, campos de preço, versão, ano, câmbio e galeria. O plugin próprio controla cadastro e API. O tema apenas exibe cards e páginas. Se o layout mudar, os dados continuam estruturados.'),
      heading('Cuidados ao criar plugin próprio'),
      list(['Nomear funções e arquivos com padrão claro.', 'Documentar campos e endpoints.', 'Evitar dependências desnecessárias.', 'Tratar segurança e permissões.', 'Separar administração, front-end e integrações.', 'Versionar no Git.']),
      callout('A Tehkné cria plugins próprios quando o WordPress precisa virar operação estruturada, não apenas site com plugins acumulados.', 'Planejar plugin próprio')
    ]
  },
  {
    title: 'Como automatizar atendimento comercial sem perder contexto humano',
    slug: 'como-automatizar-atendimento-comercial-sem-perder-contexto-humano',
    description: 'Veja como usar formulários, WhatsApp, CRM, automações e IA para acelerar atendimento comercial sem transformar o relacionamento em resposta genérica.',
    category: 'IA & Automações',
    tags: ['Automação comercial', 'WhatsApp', 'CRM', 'IA', 'Leads'],
    cover: '/images/blog/como-automatizar-atendimento-comercial-sem-perder-contexto-humano-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-09',
    readingTime: '15 min de leitura',
    intro: 'Atendimento comercial precisa ser rápido, mas não pode ser vazio. A automação certa coleta contexto, organiza dados e prepara o time para responder melhor, sem fingir que tudo deve ser resolvido por robô.',
    imageSuggestions: images('como-automatizar-atendimento-comercial-sem-perder-contexto-humano', 'Automação comercial', 'sales automation whatsapp crm ai leads'),
    blocks: [
      paragraph('A automação comercial começa antes do chatbot. Ela começa no formulário, na pergunta certa, na origem do lead, na classificação da demanda e no registro do histórico. Quanto melhor a entrada, melhor o atendimento humano depois.'),
      heading('O que automatizar primeiro'),
      list(['Captura de lead com campos úteis.', 'Mensagem contextual para WhatsApp.', 'Registro em CRM ou planilha controlada.', 'Notificação para o responsável.', 'Classificação por serviço, urgência e orçamento.', 'Resumo do briefing.', 'Lembrete de follow-up.']),
      paragraph('Essas automações economizam tempo sem desumanizar o atendimento. O cliente continua falando com uma pessoa, mas essa pessoa recebe mais contexto e perde menos tempo copiando dados.'),
      heading('Fluxo recomendado'),
      diagram('Formulário qualificado\n        ↓\nRegistro do lead\n        ↓\nMensagem contextual no WhatsApp\n        ↓\nCRM ou planilha\n        ↓\nResumo e próxima ação\n        ↓\nFollow-up assistido'),
      heading('Onde a IA entra'),
      paragraph('IA pode resumir briefing, sugerir perguntas, classificar tipo de projeto, detectar urgência e preparar uma resposta inicial. Mas propostas, promessas, valores e decisões sensíveis devem continuar com validação humana.'),
      heading('Erros comuns'),
      list(['Criar chatbot sem base de conhecimento.', 'Pedir informações demais logo no primeiro contato.', 'Enviar mensagens automáticas genéricas.', 'Não registrar origem e interesse do lead.', 'Não ter follow-up.', 'Não medir conversão por canal.']),
      heading('Como manter o contexto humano'),
      list(['Avisar que a mensagem foi preparada com base no briefing.', 'Dar opção de falar com uma pessoa.', 'Usar automação para organizar, não para empurrar.', 'Registrar histórico para evitar perguntas repetidas.', 'Personalizar a próxima ação conforme interesse real.']),
      callout('A Tehkné pode estruturar seu formulário, WhatsApp, CRM e automações para acelerar atendimento sem perder qualidade comercial.', 'Automatizar atendimento')
    ]
  },
  {
    title: 'Chatbot com IA para WhatsApp: quando faz sentido e quando não faz',
    slug: 'chatbot-com-ia-para-whatsapp-quando-faz-sentido',
    description: 'Guia prático para decidir se sua empresa precisa de chatbot com IA no WhatsApp, quais riscos evitar e como começar com segurança.',
    category: 'IA & Automações',
    tags: ['Chatbot', 'WhatsApp', 'IA', 'Atendimento', 'Automação'],
    cover: '/images/blog/chatbot-com-ia-para-whatsapp-quando-faz-sentido-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-10',
    readingTime: '15 min de leitura',
    intro: 'Chatbot com IA para WhatsApp pode melhorar atendimento, triagem e velocidade. Mas também pode gerar frustração se for criado sem base de conhecimento, limites, handoff humano e objetivo claro.',
    imageSuggestions: images('chatbot-com-ia-para-whatsapp-quando-faz-sentido', 'Chatbot com IA para WhatsApp', 'ai chatbot whatsapp customer service automation'),
    blocks: [
      paragraph('Antes de pensar em chatbot, a empresa precisa entender o que quer resolver: responder dúvidas repetidas, qualificar leads, enviar segunda via, consultar status, abrir chamados, agendar atendimento ou orientar próximos passos. Cada objetivo exige arquitetura diferente.'),
      heading('Quando faz sentido'),
      list(['Há volume alto de perguntas repetidas.', 'Existe base de conhecimento confiável.', 'O atendimento humano está sobrecarregado.', 'A triagem inicial consome muito tempo.', 'O cliente precisa de respostas fora do horário comercial.', 'Os processos têm regras claras e limites definidos.']),
      heading('Quando não faz sentido'),
      list(['A empresa ainda não sabe quais perguntas recebe.', 'As respostas dependem de análise humana caso a caso.', 'Não existe conteúdo confiável para alimentar a IA.', 'A marca não aceita risco de resposta imprecisa.', 'O atendimento atual não tem processo mínimo.']),
      subheading('Handoff humano'),
      paragraph('Todo chatbot sério precisa saber quando parar. Se a pessoa está irritada, se a dúvida envolve valor, contrato, reclamação ou situação sensível, o fluxo deve transferir para humano ou registrar chamado com prioridade.'),
      heading('Como começar com segurança'),
      list(['Mapear perguntas frequentes.', 'Criar base de conhecimento revisada.', 'Definir o que o bot pode e não pode responder.', 'Registrar conversas e métricas.', 'Criar fallback para humano.', 'Testar com usuários internos antes de liberar.']),
      heading('WhatsApp Business, Cloud API e ferramentas externas'),
      paragraph('Existem caminhos simples e avançados. O WhatsApp Business App resolve respostas rápidas básicas. A Cloud API permite integrações mais robustas, mas exige configuração. Ferramentas externas podem acelerar, porém precisam ser avaliadas por custo, estabilidade, termos de uso e segurança.'),
      callout('A Tehkné pode mapear se chatbot com IA faz sentido para sua operação e desenhar um fluxo seguro antes de contratar ferramenta.', 'Avaliar chatbot')
    ]
  },
  {
    title: 'Quanto custa um site profissional em 2026? O que realmente entra no orçamento',
    slug: 'quanto-custa-um-site-profissional-em-2026',
    description: 'Entenda os fatores que influenciam o preço de um site profissional: estratégia, design, páginas, SEO, CMS, integrações, performance e manutenção.',
    category: 'Sites de Alta Performance',
    tags: ['Preço de site', 'Site profissional', 'SEO', 'UX/UI', 'WordPress'],
    cover: '/images/blog/quanto-custa-um-site-profissional-em-2026-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-11',
    readingTime: '16 min de leitura',
    intro: 'Perguntar quanto custa um site profissional é como perguntar quanto custa uma sede comercial. A resposta depende do tamanho, objetivo, estrutura, acabamento, operação e manutenção.',
    imageSuggestions: images('quanto-custa-um-site-profissional-em-2026', 'Preço de site profissional', 'website pricing professional web design cost'),
    blocks: [
      paragraph('O preço de um site profissional varia porque existem níveis diferentes de entrega. Uma página simples não custa o mesmo que um site institucional com estratégia, copy, UX/UI, SEO, blog, portfólio, formulários, integrações, Analytics e manutenção.'),
      heading('O que influencia o valor'),
      list(['Número de páginas.', 'Complexidade do design.', 'Necessidade de copywriting.', 'SEO técnico e conteúdo.', 'CMS ou painel de edição.', 'Integrações com WhatsApp, CRM, ERP ou automações.', 'Performance e otimização mobile.', 'Animações e microinterações.', 'Prazo de entrega.', 'Suporte e manutenção após o lançamento.']),
      heading('Faixas comuns de projeto'),
      list(['Landing page estratégica: indicada para campanha, oferta específica ou validação rápida.', 'Site institucional profissional: home, serviços, sobre, portfólio, blog e contato.', 'Site premium ou plataforma: visual mais customizado, conteúdo estruturado, integrações e componentes sob medida.', 'Projeto recorrente: site mais manutenção, SEO, campanhas e evolução.']),
      subheading('Por que barato pode sair caro'),
      paragraph('Um site barato pode resolver presença inicial, mas pode falhar em performance, SEO, conversão, manutenção e escalabilidade. Se a empresa precisar refazer tudo em poucos meses, o barato vira retrabalho.'),
      heading('Como pedir orçamento do jeito certo'),
      list(['Explique objetivo comercial.', 'Liste páginas desejadas.', 'Mostre referências.', 'Diga se precisa de blog ou CMS.', 'Informe integrações necessárias.', 'Defina prazo e orçamento aproximado.', 'Explique quem vai atualizar o site depois.']),
      heading('O que a Tehkné considera em um diagnóstico'),
      paragraph('A Tehkné avalia posicionamento, jornada, SEO, conteúdo, tecnologia, integrações, manutenção e potencial de evolução. O objetivo é propor uma solução que faça sentido para o momento da empresa, sem vender complexidade desnecessária.'),
      callout('Quer entender qual faixa de site faz sentido para sua empresa agora? A Tehkné pode montar um diagnóstico e plano por etapas.', 'Solicitar orçamento')
    ]
  },
  {
    title: 'Landing page ou site institucional: qual sua empresa precisa agora?',
    slug: 'landing-page-ou-site-institucional-qual-sua-empresa-precisa',
    description: 'Compare landing page e site institucional para escolher a melhor solução conforme campanha, posicionamento, SEO, geração de leads e maturidade da empresa.',
    category: 'Sites de Alta Performance',
    tags: ['Landing page', 'Site institucional', 'Conversão', 'SEO', 'Campanhas'],
    cover: '/images/blog/landing-page-ou-site-institucional-qual-sua-empresa-precisa-cover.jpg',
    author: 'Tehkné Solutions',
    date: '2026-06-12',
    readingTime: '14 min de leitura',
    intro: 'Landing page e site institucional não competem; eles resolvem momentos diferentes. A escolha certa depende do objetivo: campanha, validação de oferta, autoridade, SEO, portfólio ou presença institucional completa.',
    imageSuggestions: images('landing-page-ou-site-institucional-qual-sua-empresa-precisa', 'Landing page ou site institucional', 'landing page corporate website conversion seo'),
    blocks: [
      paragraph('Uma landing page é focada em uma ação. Um site institucional organiza a presença completa da empresa. A landing tende a ser melhor para campanha e oferta específica. O site tende a ser melhor para autoridade, SEO e visão institucional.'),
      heading('Quando escolher landing page'),
      list(['Campanha de tráfego pago.', 'Lançamento de produto ou serviço.', 'Validação de oferta.', 'Captação de leads para uma solução específica.', 'Evento, lista de espera ou pré-venda.', 'Prazo curto e objetivo único.']),
      heading('Quando escolher site institucional'),
      list(['A empresa precisa explicar várias soluções.', 'Há necessidade de ranquear no Google.', 'O cliente precisa ver portfólio e prova.', 'A marca precisa de presença institucional sólida.', 'O time precisa publicar conteúdo recorrente.', 'A operação exige páginas por serviço e contato qualificado.']),
      heading('Quando usar os dois'),
      paragraph('Empresas maduras usam site institucional como base e landing pages para campanhas específicas. O site gera autoridade e indexação. As landing pages testam mensagens, públicos e ofertas com mais foco.'),
      heading('Critérios de decisão'),
      list(['Existe uma única oferta ou várias?', 'O tráfego virá de anúncio ou busca orgânica?', 'A empresa precisa de blog?', 'Há portfólio ou cases?', 'O objetivo é vender agora ou construir autoridade?', 'O orçamento permite evolução por fases?']),
      heading('Erro comum'),
      paragraph('Muitas empresas tentam colocar todo o conteúdo institucional em uma landing page. O resultado é uma página longa, confusa e pouco focada. Outras criam site completo quando só precisavam validar uma oferta. Estratégia evita desperdício.'),
      callout('A Tehkné pode definir se sua empresa precisa de landing page, site institucional ou uma arquitetura combinada para campanha e SEO.', 'Escolher melhor caminho')
    ]
  }
];
